techpack: audio: Address unused result warning
techpack/audio/dsp/adsp-loader.c:141:3: error: ignoring return value of
function declated with 'warn_unused_result' attribute [-Werror,
-Wunused-result]
		regulator_enable(vdd_1v8);
		^~~~~~~~~~~~~~~~ ~~~~~~~
1 error generated.

Change-Id: Ief9916148e438849a923e65bdd19974e5a585bad